//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int id_cars { get; set; }
        public string CarsModel { get; set; }
        public string CarsBrand { get; set; }
        public int Price { get; set; }
        public string image { get; set; }
    }
}
